# Generated by Django 3.1.3 on 2022-09-29 16:22

from django.db import migrations
from django.db.migrations import RunPython
from django_q.models import Schedule
from django_q.tasks import schedule


def add_schedules(apps, schema_editor):
    schedule(
        "documents.tasks.update_all_documents",
        name="Update all documents",
        schedule_type=Schedule.DAILY,
    )


def remove_schedules(apps, schema_editor):
    Schedule.objects.filter(func="documents.tasks.update_all_documents").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1003_mime_types"),
        ("django_q", "0014_schedule_cluster"),
    ]

    operations = [RunPython(add_schedules, remove_schedules)]
